services:
  lint:
    image: buildkite/plugin-linter
    command: ["--id", "cultureamp/kafka-schema-check"]
    volumes:
      - ".:/plugin:ro"
  tests:
    image: buildkite/plugin-tester
    volumes:
      - ".:/plugin:ro"
