name: Kafka Schema Check
description: >
  Check if your consumed service has different version of Avro schema in your
  local against our Kafka Schema Registry
author: https://github.com/cultureamp
requirements: []
configuration:
  properties:
    schema-name:
      type: string
  additionalProperties: false
