#!/bin/bash

set -euo pipefail


schema_names_from_env=()

prefix="BUILDKITE_PLUGIN_KAFKA_SCHEMA_CHECK_SCHEMA_NAMES"

# Loop through all environment variables
for var in $(env | grep "^$prefix"); do
  IFS="=" read -ra parts <<< "$var"

  schema_names_from_env+=(${parts[1]})
done


files=$(ls)

# Output the list of files
echo "Current files in the directory:"
echo "$files"

dir="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"

# shellcheck source=lib/download.bash
. "$dir/../lib/download.bash"

download_binary_and_run "${schema_names_from_env[@]}" || exit 1
